baseurl = "www.asinclair.io"
googleAnalytics = "UA-120966199-1"
hasCJKLanguage = false
languageCode = "en"
theme = "hugo-theme-cactus-plus"
title = "Blog of Andrew Sinclair"
[params]
about = ""
archive = ""
author = "Andrew Sinclair"
baiduanalytics = ""
bio = "Software Engineer, Tools & Infrastructure @ Google"
copyright = ""
customcss = []
customjs = []
description = "Random knowledge from Andrew"
disqusshortname = ""
enablebaiduanalytics = false
enabledisqus = true
enablegoogleanalytics = true
enablerss = true
enableshare = true
enablesummary = true
enabletoc = true
enabletwittercard = true
facebook = "your_facebook_id"
home = ""
iconfont = "font-awesome"
newerposts = ""
olderposts = ""
readmore = ""
share = ""
showlatestposts = false
socialiconstyle = ""
subscribe = ""
subtitle404 = ""
title404 = ""
tweet = ""
twitter = "@theajsinclair"
twittercardimage = ""
usedescriptionreplacesummary = false
[social]
github-square = "https://www.github.com/ajsinclair"
twitter-square = "https://www.twitter.com/theajsinclair"
