baseurl = "your_site_url_address"
googleAnalytics = "your_google_analytics_id"
hasCJKLanguage = false
languageCode = "en"
theme = "hugo-theme-cactus-plus"
title = "site title"
[params]
about = ""
archive = ""
author = "Andrew Sinclair"
baiduanalytics = ""
bio = "author biography"
copyright = ""
customcss = []
customjs = []
description = "Site Description"
disqusshortname = ""
enablebaiduanalytics = false
enabledisqus = true
enablegoogleanalytics = true
enablerss = true
enableshare = true
enablesummary = true
enabletoc = true
enabletwittercard = true
facebook = "your_facebook_id"
home = ""
iconfont = "font-awesome"
newerposts = ""
olderposts = ""
readmore = ""
share = ""
showlatestposts = false
socialiconstyle = ""
subscribe = ""
subtitle404 = ""
title404 = ""
tweet = ""
twitter = "@theajsinclair"
twittercardimage = ""
usedescriptionreplacesummary = false
[social]
facebook-square = "https://www.facebook.com/nodejh"
github-square = "https://www.github.com/nodejh"
twitter-square = "https://www.twitter.com/nodejh"
